### ISSUE TITLE
Spacebars / blaze update

### ISSUE THREAD

**Issue by ryw** [cmather/meteor-handlebars-server#12]
Testing some of our apps w/ blaze-rc0 — we use handlebars-server with a standard route to do 404s server side:

```
  @route 'notFound',
    path: '*'
    where: 'server'
    action: ->
      @response.statusCode = 404
      @response.end Handlebars.templates['404']()
```

This is broken for us w/ blaze — think this package will be fairly easy to blazify?

**Comment by cmather** [comment]
I might need to do an atmosphere release. Does it work with master?

**Comment by ryw** [comment]
Hmm, testing w/ master I get a new error...

```
W20140228-02:55:56.180(-5)? (STDERR) TypeError: Cannot set property '404' of undefined
W20140228-02:55:56.180(-5)? (STDERR)     at app/server/views/handlebars.404.js:1:444
W20140228-02:55:56.180(-5)? (STDERR)     at app/server/views/handlebars.404.js:3:3
W20140228-02:55:56.180(-5)? (STDERR)     at /Users/ry/code/assistant2/.meteor/local/build/programs/server/boot.js:155:10
W20140228-02:55:56.180(-5)? (STDERR)     at Array.forEach (native)
W20140228-02:55:56.181(-5)? (STDERR)     at Function._.each._.forEach (/Users/ry/.meteor/tools/6c38ffe2fb/lib/node_modules/underscore/underscore.js:79:11)
W20140228-02:55:56.181(-5)? (STDERR)     at /Users/ry/code/assistant2/.meteor/local/build/programs/server/boot.js:82:5
```

The compiled template looks like this:

```
(function(){Handlebars = Handlebars || {templates: {}};var template = OriginalHandlebars.compile("<!DOCTYPE html>\n<html>\n  <head>\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title></title>\n  </head>\n  <body>\n    Oops, this page can't be found.\n  </body>\n</html>\n");Handlebars.templates["404"] = function (data) { return template(data || {}, { helpers: OriginalHandlebars.helpers,partials: {},name: "404"});};

})();
```

So it looks like it doesn't like the `Handlebars.templates["404"]` part...

**Comment by cmather** [comment]
I may not have pushed my latest. I'll look tomorrow. If you need something now I think you just need to open the plugin file and change the handlebars declaration to two lines:  

Handlebars = Handlebars || {}
Handlebars.templates = Handlebars.templates || {}

**Comment by ryw** [comment]
Thanks Chris - that worked.

Made PR #13 for your convenience :)
