### ISSUE TITLE
Should this be able to work with < 0.6.5 ?

### ISSUE THREAD

**Issue by gabrielhpugliese** [cmather/meteor-handlebars-server#5]
I'm having this issue with version 1.1.0 and Meteor 0.6.4.1

``` javascript
Exception while bundling application:
TypeError: Object #<Object> has no method '_transitional_registerBuildPlugin'
    at /home/gpugliese/workspace/livecode/packages/handlebars-server/package.js:9:9
    at _.extend.initFromPackageDir (/home/gpugliese/.meteor/tools/d699ad29da/tools/packages.js:175:5)
    at _.extend.initFromLocalPackages (/home/gpugliese/.meteor/tools/d699ad29da/tools/packages.js:188:12)
    at Object._.extend.get (/home/gpugliese/.meteor/tools/d699ad29da/tools/packages.js:350:17)
    at self.api.use (/home/gpugliese/.meteor/tools/d699ad29da/tools/bundler.js:111:28)
    at Array.forEach (native)
    at Function._.each._.forEach (/home/gpugliese/.meteor/tools/d699ad29da/lib/node_modules/underscore/underscore.js:78:11)
    at Object.self.api.use (/home/gpugliese/.meteor/tools/d699ad29da/tools/bundler.js:110:9)
    at _.extend.init_from_app_dir [as on_use_handler] (/home/gpugliese/.meteor/tools/d699ad29da/tools/packages.js:238:11)
    at _.extend.use (/home/gpugliese/.meteor/tools/d699ad29da/tools/bundler.js:464:11)
    at Object.exports.bundle (/home/gpugliese/.meteor/tools/d699ad29da/tools/bundler.js:873:12)
    at /home/gpugliese/.meteor/tools/d699ad29da/tools/run.js:697:26
    at exports.inFiber (/home/gpugliese/.meteor/tools/d699ad29da/tools/fiber-helpers.js:24:12)

```

**Comment by cmather** [comment]
Hey Gabriel, Unfortunately the latest version will only work with 0.6.5. If you need to use a previous version, you can update your smart.json file to point to the previous version of handlebars-server.

**Comment by gabrielhpugliese** [comment]
OK. Thanks.
